### ISSUE TITLE
Translate README.md to english

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [MarcoDiFrancesco/HomeAutomation#1]
Translate [README.md](https://github.com/MarcoDiFrancesco/HomeAutomation/blob/master/README.md)

**Comment by PietroMezzaroba** [comment]
Ok

Il Sab 5 Ott 2019, 20:08 Marco Di Francesco <notifications@github.com> ha
scritto:

**Comment by MarcoDiFrancesco** [comment]
Bravo contribuisci

**Comment by PietroMezzaroba** [comment]
Perfetto
